apiVersion: v1
kind: Pod
metadata:
  name: busybox
  namespace: dev-apps
spec:
#  nodeName: gke-dev-cluster-dev-nsq-node-pool-8fbcc515-ium2
  tolerations:
  - effect: NoSchedule
    key: dev-nsq-node-pool
    operator: Equal
    value: "true"
  containers:
  - image: busybox
#    command: [ "/bin/bash", "-c", "--" ]
#    args: [ "while true; do sleep 30; done;" ]
    command:
      - sleep
      - "60000"
    imagePullPolicy: IfNotPresent
    name: busybox
#    volumeMounts:
#        - mountPath: /data
#          name: data
  restartPolicy: Always
#  volumes:
#  - name: data
#    persistentVolumeClaim:
#      claimName: data-nsq-nsqd-1        

