apiVersion: v1
kind: Pod
metadata:
  name: redis
  namespace: prod-apps
spec:
  containers:
  - image: redis
    command:
      - tail
      - -f
      - /dev/null
    imagePullPolicy: IfNotPresent
    name: redis
  restartPolicy: Always
